[package]
name = "llama"
author = "Frelerik"
content_root = "src"
version = "1.1.0"
license = "MIT"
dependencies_root = "src"

[dependencies]
t = { git = "https://github.com/osyrisrblx/t", rev = "e2c5599" }
